name: release

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang Environment
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Setup ghr
        env:
          GO11MODULE: on
          GOPATH: /home/runner/tools
        run: go get -u github.com/tcnksm/ghr
      - name: Release
        env:
          GOPATH: /home/runner/tools
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export CREATE_EVENT_REF_TYPE=$(jq --raw-output .ref_type "$GITHUB_EVENT_PATH")
          export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
          echo $TAG_NAME
          if [ "$CREATE_EVENT_REF_TYPE" != "tag" ]; then echo "ref_type is not a tag: ${CREATE_EVENT_REF_TYPE}" && exit 78; fi
          $GOPATH/bin/ghr -n ${TAG_NAME} -b "Release ${TAG_NAME}" -draft ${TAG_NAME} build/release/
